export enum StaffActionType {
  FETCH_ALL_STAFF = "FETCH_ALL_STAFF",
  FETCH_STAFF_BY_ID = "FETCH_STAFF_BY_ID",
  CREATE_STAFF = "CREATE_STAFF",
  UPDATE_STAFF = "UPDATE_STAFF",
  DELETE_STAFF = "DELETE_STAFF",
  TOGGLE_FLIPPED = "TOGGLE_FLIPPED",
  SET_COUNTRIES = "SET_COUNTRIES",
  SET_STATES = "SET_STATES",
  SET_FLIPPED_SIDE_STATE = "SET_FLIPPED_SIDE_STATE"
}

export interface StaffAction {
  type: StaffActionType;
  payload?: any;
}
