export enum GradeLevelActionType {
  ADD_GRADE_LEVEL = "ADD_GRADE_LEVEL",
  UPDATE_GRADE_LEVEL = "UPDATE_GRADE_LEVEL",
  DELETE_GRADE_LEVEL = "DELETE_GRADE_LEVEL",
  FETCH_GRADE_LEVELS = "FETCH_GRADE_LEVELS",
  FETCH_GRADE_LEVEL_BY_ID = "FETCH_GRADE_LEVEL_BY_ID",
  TOGGLE_LEVEL_FLIPPED = "TOGGLE_LEVEL_FLIPPED",
  SET_FLIPPED_SIDE_STATE = "SET_FLIPPED_SIDE_STATE"
}

export interface GradeLevelAction {
  type: GradeLevelActionType;
  payload?: any;
}
